default: &default
  ezid_pass: apitest
  ezid_user: apitest
  fedora_user: fedoraAdmin
  hydra_postgres_db: my_hydra_db
  hydra_postgres_user: my_hydra_pg_user
  hydra_postgres_pass: boca-locale-food-marked
  ldap_ad_admin_pass: 'Hydra4Me!'
  ldap_ad_admin_user: 'adrl@library.ucsb.edu'
  ldap_ad_group_base: dc=library,dc=ucsb,dc=edu
  ldap_ad_host: dc.library.ucsb.edu
  ldap_campus_admin_pass: b2v3wuZyeB2Ah5a7
  ldap_campus_admin_user: uid=adrlrepo,ou=applications,o=ucsb
  ldap_campus_group_base: ou=People,o=ucsb
  ldap_campus_host: ldap.ucsb.edu
  marmotta_host: localhost
  pg_pass: parasol-arose-lethargy-domain
  secret_key_base: 7faf7ade789348ced1c488f47bd671801a419ca165f548a0c4d376b6f94a5889
  smtp_host: sendmail-relay-2476.library.ucsb.edu
  sru_host: "https://ucsb.alma.exlibrisgroup.com/view/sru/01UCSB_INST"
  ezid_default_shoulder: "ark:/99999/fk4"

development:
  <<: *default
  contact_us_email_to: adunn@ucsb.edu
  fedora_pass: gaiter-hyphen-you-laramie

test:
  <<: *default
  contact_us_email_to: adunn@ucsb.edu
  fedora_pass: fedoraAdmin
